/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.encosoft.vista;

import com.encosoft.controlador.ControlAgencia;
import com.encosoft.controlador.ControlDetalleEncomienda;
import com.encosoft.controlador.ControlEncomienda;
import com.encosoft.controlador.ControlReportes;
import com.encosoft.dtos.ListarDetalleEncomiendasDTO;
import com.encosoft.dtos.ListarEncomiendasDTO;
import com.encosoft.modelo.Agencia;
import com.encosoft.util.Constantes;
import com.encosoft.util.Utilitario;
import com.itextpdf.text.DocumentException;
import java.io.IOException;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author echamaya
 */
public class ListarEncomiendas extends javax.swing.JInternalFrame {

    Map<Integer, String> agenciaMap = new HashMap<>();

    String cliente = "", receptor = "";

    /**
     * Creates new form ListarEncomiendas
     */
    public ListarEncomiendas() {
        initComponents();
        listarEncomienda();
        pnlDetalle.setVisible(false);
    }

    void listarEncomienda() {
        DefaultTableModel modelo = new DefaultTableModel() {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        ControlEncomienda controlEncomienda = new ControlEncomienda();

        tblEncomiendas.setModel(modelo);
        modelo.addColumn("ID");
        modelo.addColumn("AGENCIA");
        modelo.addColumn("CLIENTE");
        modelo.addColumn("RECEPTOR");
        modelo.addColumn("FECHA");
        modelo.addColumn("PRECIO");
        modelo.addColumn("ESTADO");

        modelo.setRowCount(0);
        List<ListarEncomiendasDTO> lista = controlEncomienda.listarEncomiendasPersonalizado(cliente, receptor, "");
        for (ListarEncomiendasDTO e : lista) {
            Object data[] = {e.getId(), e.getAgencia(), e.getCliente(), e.getReceptor(), e.getFecha(), e.getPrecio(), e.getEstado()};
            modelo.addRow(data);
        }
        Utilitario.ocultarColumnas(tblEncomiendas, 0);
    }

    void listarDetalleEncomienda(int idEncomienda) {
        DefaultTableModel modelo = new DefaultTableModel() {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        ControlDetalleEncomienda controlDetalleEncomienda = new ControlDetalleEncomienda();

        tblDetalle.setModel(modelo);
        modelo.addColumn("CATEGORIA");
        modelo.addColumn("PRODUCTO");
        modelo.addColumn("PESO");
        modelo.addColumn("CANTIDAD");
        modelo.addColumn("PRECIO UNIT");
        modelo.addColumn("TOTAL");

        modelo.setRowCount(0);
        List<ListarDetalleEncomiendasDTO> lista = controlDetalleEncomienda.listarDetalleEncomiendaPersonalizado(idEncomienda);
        for (ListarDetalleEncomiendasDTO d : lista) {
            Object data[] = {d.getCategoria(), d.getProducto(), d.getPeso(), d.getCantidad(), d.getPrecioUnitario(), d.getTotal()};
            modelo.addRow(data);
        }
        tblDetalle.clearSelection();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblEncomiendas = new javax.swing.JTable();
        pnlDetalle = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblDetalle = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        txtCliente = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtReceptor = new javax.swing.JTextField();
        btnBuscarEncomienda = new javax.swing.JButton();
        btnListarTodo = new javax.swing.JButton();
        btnDescargarEncomienda = new javax.swing.JButton();

        setClosable(true);
        setTitle("LISTADO DE ENCOMIENDAS");

        jPanel1.setBackground(new java.awt.Color(51, 0, 153));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("LISTADO DE ENCOMIENDAS");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        tblEncomiendas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblEncomiendas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblEncomiendasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblEncomiendas);

        pnlDetalle.setBorder(javax.swing.BorderFactory.createTitledBorder("Detalle de encomienda"));

        tblDetalle.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tblDetalle);

        javax.swing.GroupLayout pnlDetalleLayout = new javax.swing.GroupLayout(pnlDetalle);
        pnlDetalle.setLayout(pnlDetalleLayout);
        pnlDetalleLayout.setHorizontalGroup(
            pnlDetalleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDetalleLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 752, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlDetalleLayout.setVerticalGroup(
            pnlDetalleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDetalleLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel5.setText("CLIENTE:");

        jLabel6.setText("RECEPTOR:");

        btnBuscarEncomienda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/lupa-pequena.png"))); // NOI18N
        btnBuscarEncomienda.setText("BUSCAR ENCOMIENDA");
        btnBuscarEncomienda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarEncomiendaActionPerformed(evt);
            }
        });

        btnListarTodo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/lupa-pequena.png"))); // NOI18N
        btnListarTodo.setText("LISTAR TODO");
        btnListarTodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarTodoActionPerformed(evt);
            }
        });

        btnDescargarEncomienda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/descargar-encomienda.png"))); // NOI18N
        btnDescargarEncomienda.setText("DESCARGAR ENCOMIENDA");
        btnDescargarEncomienda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDescargarEncomiendaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1)
            .addComponent(pnlDetalle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 378, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtReceptor)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnDescargarEncomienda)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnBuscarEncomienda)
                        .addGap(18, 18, 18)
                        .addComponent(btnListarTodo)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtReceptor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnBuscarEncomienda)
                        .addComponent(btnListarTodo))
                    .addComponent(btnDescargarEncomienda))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlDetalle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblEncomiendasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblEncomiendasMouseClicked
        int filaSeleccionada = tblEncomiendas.getSelectedRow();
        if (filaSeleccionada >= 0) {
            pnlDetalle.setVisible(true);
            int idEncomienda = Integer.parseInt(tblEncomiendas.getValueAt(filaSeleccionada, 0).toString());
            listarDetalleEncomienda(idEncomienda);
        }
    }//GEN-LAST:event_tblEncomiendasMouseClicked

    private void btnBuscarEncomiendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarEncomiendaActionPerformed
        if (!txtCliente.getText().trim().isEmpty() || !txtReceptor.getText().trim().isEmpty()) {
            cliente = txtCliente.getText();
            receptor = txtReceptor.getText();
            listarEncomienda();
            ((DefaultTableModel) tblDetalle.getModel()).setRowCount(0);
        }
    }//GEN-LAST:event_btnBuscarEncomiendaActionPerformed

    private void btnListarTodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarTodoActionPerformed
        Utilitario.limpiarTextbox(txtCliente, txtReceptor);
        cliente = "";
        receptor = "";
        listarEncomienda();
        ((DefaultTableModel) tblDetalle.getModel()).setRowCount(0);
    }//GEN-LAST:event_btnListarTodoActionPerformed

    private void btnDescargarEncomiendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDescargarEncomiendaActionPerformed
        int filaSeleccionada = tblEncomiendas.getSelectedRow();
        if (filaSeleccionada >= 0) {
            int idEncomienda = Integer.parseInt(tblEncomiendas.getValueAt(filaSeleccionada, 0).toString());
            ControlReportes controlReportes = new ControlReportes();
            try {
                controlReportes.descargarEncomienda(idEncomienda);
                JOptionPane.showMessageDialog(null, "Descarga exitosa", Constantes.TITULO_MENSAJE, JOptionPane.INFORMATION_MESSAGE);
                tblEncomiendas.clearSelection();
            } catch (DocumentException | IOException ex) {
                Logger.getLogger(ListarEncomiendas.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            Utilitario.MensajeSeleccionarRegistro();
        }
    }//GEN-LAST:event_btnDescargarEncomiendaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarEncomienda;
    private javax.swing.JButton btnDescargarEncomienda;
    private javax.swing.JButton btnListarTodo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel pnlDetalle;
    private javax.swing.JTable tblDetalle;
    private javax.swing.JTable tblEncomiendas;
    private javax.swing.JTextField txtCliente;
    private javax.swing.JTextField txtReceptor;
    // End of variables declaration//GEN-END:variables
}
